baseURL = "https://opentr.foundation"
title = "OpenTR"

# Language settings
contentDir = "content/tr"
defaultContentLanguage = "tr"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = []

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = []

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = []


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-SP3T9XWG2M"

# Language configuration

[languages.tr]
title = "OpenTR"
description = "OpenTR Türkiye'de açık kaynak projelere katkıda bulunmakta zorluk çeken kuruluş ve bireylerin bu zorluğu aşmasına yardımcı olan bir oluşumdur."
languageName ="🇹🇷 Türkçe"
contentDir = "content/tr"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"
# Weight used for sorting.
weight = 1
[languages.tr.params]
# First one is picked as the Twitter card image if not set on page.
images = ["images/open-tr-banner-01-opengraph-card.png"]

[languages]
[languages.en]
title = "OpenTR"
description = "OpenTR provides open source strategy and guidance for organizations and individuals in Turkey."
languageName ="🇬🇧 English"
contentDir = "content/en"
# Weight used for sorting.
weight = 2
[languages.en.params]
# First one is picked as the Twitter card image if not set on page.
images = ["images/open-tr-banner-01-opengraph-card-en.png"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
# RSS is needed if you need print support.
# See https://www.docsy.dev/docs/adding-content/print/
[outputs]
section = ["HTML", "print", "RSS"]

[params]
# copyright = "The OpenTR Authors"

# No privacy policy
# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://opentr.foundation"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
# TODO: to be updated
github_repo = "https://github.com/OpenTRFoundation/opentr"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
# TODO: to be updated
# github_project_repo = "https://github.com/OpenTRFoundation/opentr"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "1637cc6af98914810"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

[params.mermaid]
enable = true

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#  name = "İletişim"
#  url = "/contact/"
#  icon = "fa fa-user"
#
#[[params.links.user]]
#  name = "Tartışma forumu"
#  url = "https://github.com/orgs/OpenTRFoundation/discussions"
#  icon = "fa fa-comments"
#
#[[params.links.user]]
#  name ="Twitter"
#  url = "https://twitter.com/opentr_fdn"
#  icon = "fab fa-twitter"
#
#[[params.links.user]]
#  name ="LinkedIn"
#  url = "https://www.linkedin.com/company/open-tr/"
#  icon = "fab fa-linkedin"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
#[[params.links.developer]]
#  name = "GitHub"
#  url = "https://github.com/OpenTRFoundation/opentr"
#  icon = "fab fa-github"
#
#[[params.links.developer]]
#  name = "Slack"
#  url = "https://join.slack.com/t/open-tr/shared_invite/zt-2045iugc5-VgCozOqAqs297Cws7m~vgw"
#  icon = "fab fa-slack"

#[[params.links.developer]]
#  name = "Duyuru Listesi"
#  url = "https://groups.google.com/a/opentr.foundation/g/duyuru"
#  icon = "fa fa-envelope"

# hugo module configuration

[module]
  #replacements = "github.com/OpenTRFoundation/opentr-docsy-custom -> /absolute/path/to/opentr-docsy-custom"
  [module.hugoVersion]
    extended = true
    min = "0.111.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
